### ISSUE TITLE
Restructure the layout of the tutorial into a GitBook

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-apple-watch-development#18]
After having the standup on 1st December, Ines/Nelson recommended that we update the layout of the tutorial. 

It needs to be:
- **easy to follow** for both beginners/non-beginners
- clear structure, something along the lines of this https://github.com/evancz/guide.elm-lang.org

**Comment by nelsonic** [comment]
@sohilpandya the _reason_ for recommending a `GitBook` https://www.gitbook.com/ is because it creates a _linear_ learning process which _I_ find _useful_ when learning something _from scratch_. 😉

**Comment by sohilpandya** [comment]
I am planning to tackle this in the afternoon today, I was going to setup a GitBook with the following structure, to begin with:
```
- Introduction to Learn Apple Watch Development
- Installation
- Basics of Swift
  - variables
  - control flow
  - functions
  - etc.
- Tutorials
  - iPhone
    - Calculator
    - FoodTracker
  - Apple Watch
    - Simple Counter
  - iPhone + Apple Watch
    - Interaction App (interaction on AW to represent changes on iPhone)
```

How does that look @nelsonic?

**Comment by nelsonic** [comment]
@sohilpandya looks like a _good_ structure. (_can always be incrementally improved through user-feedback later..._) 👍

**Comment by sohilpandya** [comment]
Thanks @nelsonic for merging the PR! 👍 

I thought that PR would solve the issue of the [GitBook](https://www.gitbook.com/book/sohilpandya/learn-apple-watch-development/details) not showing up correctly, but it doesn't seem to have done the trick. 😢 

I'll have to look into why the `summary.md` page is not being recognised as the entry.

**Comment by nelsonic** [comment]
@sohilpandya good plan (_next action_) 👍 
If you're stuck with GitBook, you can always `#HelpWanted` and ask friends who do git-booking every day... 😉

**Comment by sohilpandya** [comment]
@nelsonic Thanks for that action plan, unfortunately, I won't have time until later this week to have a look at what is causing this particular issue, so I have added the `help wanted` label. Will try to sort this issue out before the Christmas break! 🎄

**Comment by nelsonic** [comment]
@sohilpandya sounds good. the repo is _already_ in pretty good shape so people can start using the tutorial to get "_up-and-running_" with `swift`... 

> **Note**: we need to get a lot more _systematic_ about our use of `help wanted` in _all_ our projects in 2017! I'm _excited_! see: https://github.com/dwyl/labels/issues/44 😉  `CC:` @markwilliamfirth

**Comment by sohilpandya** [comment]
@nelsonic do we have a `dwyl` organisation for gitbook or is it ok for me to create one?

**Comment by nelsonic** [comment]
@sohilpandya yes, we do. 
login with: hello+gitbook@dwyl.io
(_I've messaged you the password_)

**Comment by sohilpandya** [comment]
@nelsonic I'm having trouble logging into GitBook 😢 

Used both the above logins emails along with the password that you had sent me.

**Comment by nelsonic** [comment]
@sohilpandya are you @ScienceMuseum today? remind me and we can pair on logging in and setup. 👍

**Comment by sohilpandya** [comment]
@nelsonic I am @ScienceMuseum today, catch you shortly!

**Comment by sohilpandya** [comment]
@nelsonic thanks for helping out with the sign-up process I can confirm that the email address for login is  hello+gitbook@dwyl.io, there are still a couple of things that need to happen for us to link this repo to the DWYL gitbook.

- [ ] verify ownership via email
- [ ] link the GitHub organisation to this account
- [x] update user profile image

<img width="1040" alt="screen shot 2017-02-24 at 16 07 55" src="https://cloud.githubusercontent.com/assets/2305591/23310770/854eb3f8-faab-11e6-85ea-f82f63609f53.png">

**Comment by sohilpandya** [comment]
I've sent a message to GitBook with regards to us not being able to link the GitHub account. 

Currently getting this error message:
<img width="1920" alt="screen shot 2017-03-01 at 10 02 01" src="https://cloud.githubusercontent.com/assets/2305591/23456402/2ae2b892-fe6b-11e6-96c0-1c4b6b17bcca.png">

They may get back to us on the hello email, so it'd be great if you kept an eye on it! 😄

**Comment by nelsonic** [comment]
@sohilpandya you do have a @dwyl email address right? 
Have you tried emailing them?

**Comment by sohilpandya** [comment]
@nelsonic I did send a message with regards to the error above, but have just sent another one asking for steps to connect this org to the gitbook account.

**Comment by markwilliamfirth** [comment]
<img width="546" alt="screen shot 2017-03-07 at 09 05 10" src="https://cloud.githubusercontent.com/assets/5732209/23649139/3cfbc8f8-0315-11e7-88f2-0cf564c70473.png">

this ok to do @nelsonic ?

**Comment by markwilliamfirth** [comment]
or should we install globally? Not sure if write access to code means it pushes to master?

**Comment by iteles** [comment]
@markwilliamfirth Write access is fine (and required for what gitbook does). We should also set up with just the repos we want for now so I agree with the way you're proposing Mark!

We can also set up master as a [protected branch](https://help.github.com/articles/about-protected-branches/) so that it can't be force pushed or deleted.

Admin access is the one that we're trying to avoid at all costs as that grants access to delete the repo itself.

**Comment by markwilliamfirth** [comment]
Cool - done!

@sohilpandya

**Comment by nelsonic** [comment]
@markwilliamfirth that _looks_ like it should work. thanks! 👍

**Comment by sohilpandya** [comment]
Thanks @markwilliamfirth for sorting that out. 

We finally have our first book on GitBooks! https://dwyl.gitbooks.io/learn-apple-watch-development/content/ :tada:
