### ISSUE TITLE
Setting up a GitBook

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-apple-watch-development#19]
Following on from the conversation we've had in #18, I'll be creating a GitBook for learn-apple-watch-development.

This issue just involves the setting up of the GitBook, restructure of the content will be done in #18 

Whilst trying to setup a GitBook, I've come across an issue where I've been unable to select this particular repo.
`dwyl/learn-apple-watch-development`
![screen shot 2016-12-05 at 14 25 51](https://cloud.githubusercontent.com/assets/2305591/20888415/c6343e64-baf6-11e6-897c-116a84ae8d4d.png)

@nelsonic/@iteles is it the case of you giving me permissions for selecting the repo? As I can't seem to find the ability to pick this or any other dwyl repos.

**Comment by iteles** [comment]
Odd! Try again?

**Comment by sohilpandya** [comment]
I've had to ask for access to DWYL on GitBook again. If you OK that then I should be good to go I think. 😄

**Comment by sohilpandya** [comment]
Thanks @iteles! 🙌

**Comment by sohilpandya** [comment]
GitBook has been setup, I'll continue to restructure the content and push it up at the end of the day (#18)
