### ISSUE TITLE
Add dwylbot to this repo 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-apple-watch-development#42]
Hey @iteles, can you please add `dwylbot` to this repo as well. 👍 

unable to add it to this repo due to the reasons related to admin rights. 

Thanks!

**Comment by nelsonic** [comment]
@sohilpandya you are admin:
![image](https://user-images.githubusercontent.com/194400/27510982-f51aa05e-5913-11e7-8ccb-2c598f34918d.png)

**Comment by iteles** [comment]
@nelsonic with github apps you have to be _org_ admin apparently.

It's a bit of a bummer until github changes this...

**Comment by iteles** [comment]
:+1:
